# Generated by Django 5.2.1 on 2025-05-19 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=15)),
                ('training_days_per_week', models.PositiveIntegerField()),
                ('training_days', models.JSONField()),
                ('training_duration_minutes', models.PositiveIntegerField()),
                ('available_equipment', models.JSONField()),
                ('preferred_location', models.CharField(choices=[('home', 'Home'), ('gym', 'Gym')], max_length=20)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', ' Male'), ('female', 'Female')], max_length=10)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('age', models.PositiveIntegerField()),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Strength'), ('aesthetics', 'Aesthetics'), ('endurance', 'Endurance')], max_length=30)),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('body_fat_percentage_interd_by_user', models.FloatField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('ectomorph', 'Ectomorph'), ('mesomorph', 'Mesomorph'), ('endomorph', 'Endomorph')], max_length=20, null=True)),
                ('daily_activity_level', models.CharField(choices=[('low', 'Low (Sedentary)'), ('moderate', 'Moderate'), ('high', 'Active)')], max_length=10)),
                ('aura', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InjuryExerciseClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury', models.CharField(choices=[('lower_back', 'Lower Back Injury'), ('knee', 'Knee Injury'), ('shoulder', 'Shoulder Injury'), ('neck', 'Neck Injury'), ('wrist', 'Wrist Injury'), ('elbow', 'Elbow Injury'), ('hip', 'Hip Injury'), ('chest', 'Chest Injury')], max_length=20)),
                ('classification', models.CharField(choices=[('avoid', 'Avoid'), ('safe', 'Safe Alternative')], max_length=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_classifications', to='exercises.exercise')),
            ],
            options={
                'unique_together': {('injury', 'exercise')},
            },
        ),
    ]
