# Generated by Django 5.2.1 on 2025-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_trainingsettings_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsettings',
            name='split_type',
            field=models.CharField(choices=[('full_body', 'Full Body'), ('upper_lower', 'Upper/Lower Split'), ('push_pull_legs', 'Push/Pull/Legs'), ('bro_split', 'Bro Split (Body Part Split)')], default='full_body', max_length=20),
        ),
    ]
