# Generated by Django 5.2.1 on 2025-05-26 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_trainingsettings_split_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsettings',
            name='split_last_updated',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='زمان آخرین به\u200cروزرسانی split'),
        ),
        migrations.AddField(
            model_name='trainingsettings',
            name='split_rotation_weeks',
            field=models.PositiveIntegerField(default=4, help_text='تعداد هفته\u200cها تا چرخش خودکار split'),
        ),
        migrations.AlterField(
            model_name='trainingsettings',
            name='split_type',
            field=models.CharField(choices=[('bro_split', 'Bro Split'), ('ppl', 'Push Pull Legs'), ('upper_lower', 'Upper Lower'), ('full_body', 'Full Body')], default='full_body', max_length=20),
        ),
    ]
