# Generated by Django 5.2.1 on 2025-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_trainingsettings_split_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_training_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ آخرین تمرین کاربر', null=True),
        ),
    ]
