# Generated by Django 5.2.1 on 2025-05-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_last_training_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='physical_limitations',
            field=models.JSONField(blank=True, default=list, help_text='List of physical limitations or injuries'),
        ),
    ]
