# Generated by Django 5.2.1 on 2025-05-31 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_physical_limitations'),
        ('exercises', '0004_remove_exercise_primary_muscles_array_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('muscle_group', models.CharField(max_length=50)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.CharField(max_length=20)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('intensity', models.FloatField(default=0.7)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='accounts.workoutday')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weeks', models.PositiveIntegerField(default=4)),
                ('split_type', models.CharField(max_length=20)),
                ('experience_level', models.CharField(max_length=15)),
                ('goal', models.CharField(max_length=30)),
                ('available_equipment', models.JSONField()),
                ('training_days', models.JSONField()),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.trainingsettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='accounts.botuser')),
            ],
        ),
        migrations.AddField(
            model_name='workoutday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='accounts.workoutplan'),
        ),
    ]
