# Generated by Django 5.2.1 on 2025-05-19 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(blank=True, null=True)),
                ('primary_muscles', models.JSONField()),
                ('secondary_muscles', models.JSONField(blank=True, null=True)),
                ('force', models.CharField(blank=True, choices=[('pull', 'Pull'), ('push', 'Push'), ('static', 'Static')], max_length=10, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=15)),
                ('mechanic', models.CharField(blank=True, choices=[('compound', 'Compound'), ('isolation', 'Isolation')], max_length=15, null=True)),
                ('equipment', models.CharField(blank=True, choices=[('body', 'Body Only'), ('machine', 'Machine'), ('kettlebells', 'Kettlebells'), ('dumbbell', 'Dumbbell'), ('cable', 'Cable'), ('barbell', 'Barbell'), ('bands', 'Bands'), ('medicine_ball', 'Medicine Ball'), ('exercise_ball', 'Exercise Ball'), ('e_z_curl_bar', 'E-Z Curl Bar'), ('foam_roll', 'Foam Roll')], max_length=20, null=True)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('stretching', 'Stretching'), ('plyometrics', 'Plyometrics'), ('strongman', 'Strongman'), ('powerlifting', 'Powerlifting'), ('cardio', 'Cardio'), ('olympic_weightlifting', 'Olympic Weightlifting'), ('crossfit', 'CrossFit'), ('weighted_bodyweight', 'Weighted Bodyweight'), ('assisted_bodyweight', 'Assisted Bodyweight')], max_length=30)),
                ('instructions', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tips', models.JSONField(blank=True, null=True)),
                ('name_in_persian', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions_in_persian', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_images/')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exercises.exercise')),
            ],
        ),
    ]
