# Generated by Django 5.0.7 on 2025-05-27 14:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscles_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscles',
            field=models.CharField(max_length=50),
        ),
    ]
