# Generated by Django 5.0.7 on 2025-05-27 14:26

from django.db import migrations, models

def copy_json_to_array(apps, schema_editor):
    Exercise = apps.get_model('exercises', 'Exercise')
    for ex in Exercise.objects.all():
        # انتقال primary_muscles
        if ex.primary_muscles:
            if isinstance(ex.primary_muscles, list):
                ex.primary_muscles_array = [str(m) for m in ex.primary_muscles]
            else:
                ex.primary_muscles_array = [str(ex.primary_muscles)]
        else:
            ex.primary_muscles_array = []
        # انتقال secondary_muscles
        if ex.secondary_muscles:
            if isinstance(ex.secondary_muscles, list):
                ex.secondary_muscles_array = [str(m) for m in ex.secondary_muscles]
            else:
                ex.secondary_muscles_array = [str(ex.secondary_muscles)]
        else:
            ex.secondary_muscles_array = []
        ex.save()

class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_remove_exercise_secondary_muscles_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_json_to_array),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscles',
            field=models.JSONField(),
        ),
    ]
