# Generated by Django 5.0.7 on 2025-05-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_secondary_muscles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscles_array',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscles_array',
        ),
    ]
