# Generated by Django 5.2.1 on 2025-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_remove_exercise_primary_muscles_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
